---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuyan.
--- DateTime: 2018/9/24 15:36
---

local Bullet = class("Bullet", function()
    return cc.Sprite:create()
end)

function Bullet.create(spriteFrameName)
    local bullet = Bullet.new(spriteFrameName)
    return bullet
end

function Bullet:ctor(spriteFrameName)
    self:setSpriteFrame(spriteFrameName)
    self:setVisible(false)
    self.velocity = Sprite_Velocity.Bullet

    local body = cc.PhysicsBody:createBox(self:getContentSize())
    body:setCategoryBitmask(0x01)
    body:setCollisionBitmask(0x02)
    body:setContactTestBitmask(0x01)

    self:setPhysicsBody(body)

    function onNodeEvent(tag)
        if tag == "exit" then
            self:unscheduleUpdate()
        end
    end

    self:registerScriptHandler(onNodeEvent)
end

function Bullet:showBulletFromFighter(fighter)
    local fighterX, fighterY = fighter:getPosition()
    self:setPosition(cc.p(fighterX, fighterY + fighter:getContentSize().height / 2))
    self:setVisible(true)

    function update(delta)
        local x, y = self:getPosition()

        self:setPosition(cc.p(x + self.velocity.x * delta, y + self.velocity.y * delta))
        x, y = self:getPosition()

        if y > size.height then
            self:setVisible(false)
            self:unscheduleUpdate()
        end
    end

    self:scheduleUpdateWithPriorityLua(update, 0)
end

return Bullet


