---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuyan.
--- DateTime: 2018/9/23 15:00
---
require "SystemConst"

local size = cc.Director:getInstance()
local frameCache = cc.SpriteFrameCache:getInstance();
local textureCache = cc.Director:getInstance():getTextureCache()
local defaults = cc.UserDefault:getInstance()
local GamePlayScene = class("GamePlayScene", function()
    return cc.Scene:create()
end)

function GamePlayScene.create()
    cclog("hello create lua")
    local _GamePlayScene = GamePlayScene.new()
    _GamePlayScene:addChild(_GamePlayScene:createLayer())
    return _GamePlayScene
end

function GamePlayScene:ctor()
    local function onNodeEvent(event)
        if event == CC_LiftCycle.Enter then
            self:onEnter()
        elseif event == CC_LiftCycle.EnterTransitionFinish then
            self:onEnterTransitionFinish()
        elseif event == CC_LiftCycle.onExitTransitionStart then
            self:onExitTransitionStart()
        elseif event == CC_LiftCycle.Exit then
            self:onExit()
        elseif event == CC_LiftCycle.cleanup then
            self:cleanup()
        end
    end
    self:registerScriptHandler(onNodeEvent)
end

function GamePlayScene:createLayer()
end

function GamePlayScene:onEnter()
    cclog("GamePlayScene onEnter")

end

function GamePlayScene:onEnterTransitionFinish()
    cclog("GamePlayScene onEnterTransitionFinish")

end

function GamePlayScene:onExit()
    cclog("GamePlayScene onExit")
end

function GamePlayScene:onExitTransitionStart()
    cclog("GamePlayScene onExitTransitionStart")
end

function GamePlayScene:cleanup()
    cclog("GamePlayScene onCleanup")
end

function GamePlayScene:createLayer()
    local layer = cc.Layer:create();
    --todo add layer content
    return layer;
end

return GamePlayScene

