---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuyan.
--- DateTime: 2018/9/23 15:01
---
require "SystemConst"

local size = cc.Director:getInstance():getWinSize()
local frameCache = cc.SpriteFrameCache:getInstance();
local textureCache = cc.Director:getInstance():getTextureCache()
local defaults = cc.UserDefault:getInstance()

local HelpScene = class("HelpScene", function()
    return cc.Scene:create()
end)

function HelpScene.create()
    cclog("hello create lua")
    local _HelpScene = HelpScene.new()
    _HelpScene:addChild(_HelpScene:createLayer())
    return _HelpScene
end

function HelpScene:ctor()
    local function onNodeEvent(event)
        if event == CC_LiftCycle.Enter then
            self:onEnter()
        elseif event == CC_LiftCycle.EnterTransitionFinish then
            self:onEnterTransitionFinish()
        elseif event == CC_LiftCycle.onExitTransitionStart then
            self:onExitTransitionStart()
        elseif event == CC_LiftCycle.Exit then
            self:onExit()
        elseif event == CC_LiftCycle.cleanup then
            self:cleanup()
        end
    end
    self:registerScriptHandler(onNodeEvent)
end

function HelpScene:onEnter()
    cclog("HelpScene onEnter")

end

function HelpScene:onEnterTransitionFinish()
    cclog("HelpScene onEnterTransitionFinish")

end

function HelpScene:onExit()
    cclog("HelpScene onExit")
end

function HelpScene:onExitTransitionStart()
    cclog("HelpScene onExitTransitionStart")
end

function HelpScene:cleanup()
    cclog("HelpScene onCleanup")
end

function HelpScene:createLayer()
    local layer = cc.Layer:create();
    --todo add layer content
    local bg = cc.TMXTiledMap:create("map/red_bg.tmx")
    layer:addChild(bg)

    local top = cc.Sprite:createWithSpriteFrameName("help.page.png")
    top:setPosition(cc.p(size.width / 2, size.height - top:getContentSize().height / 2))
    layer:addChild(top)
    -- ok 菜单事件处理
    local function menuOkCallBack(sender)
        --    播放音乐
        if defaults:getBoolForKey(SOUND_KEY) then
            AudioEngine.playEffect(sound_1)
        end
        cc.Director:getInstance():popScene()
    end

    local okNormal = cc.Sprite:createWithSpriteFrameName("button.ok.png")
    local okSelected = cc.Sprite:createWithSpriteFrameName("button.ok-on.png")
    local okMenuItem = cc.MenuItemSprite:create(okNormal, okSelected)

    okMenuItem:registerScriptTapHandler(menuOkCallBack)

    local okMenu = cc.Menu:create(okMenuItem)
    okMenu:setPosition(cc.p(190, 50))
    layer:addChild(okMenu)
    return layer;
end

return HelpScene

